version: '2'

services:
  web:
    image: sng2c/lash-guard-web:latest
    environment:
      - 'VIRTUAL_HOST=lash.app.gslump.com'
      - 'LETSENCRYPT_HOST=lash.app.gslump.com'
      - 'LETSENCRYPT_EMAIL=sng2nara@gmail.com'
networks:
  default:
    external:
      name: nginx-proxy
