version: '3'

services:
  redis:
    image: sickp/alpine-redis
  web:
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - 'REDIS_HOST=redis'
